import { describe, expect, it } from "vitest";
import { mapPlaceDetailRow } from "../common/places.mappers.js";
import type { PlaceDetailRow, PlaceDetails } from "../common/places.types.js";

export function placeDetailRow(
  overrides: Partial<PlaceDetailRow> = {}
): PlaceDetailRow {
  return {
    id: 123,
    source: "google",
    source_id: "ChIJ123",
    name: "Seneca Anticafe",
    country: "romania",
    city: "bucharest",
    category: "cafe",
    primary_type: "cafe",
    types: ["cafe", "food"],
    latitude: 44.43,
    longitude: 26.1,
    formatted_address: "Bucharest",
    short_formatted_address: "Bucharest",
    business_status: "OPERATIONAL",
    google_maps_uri: "https://maps.google.com/example",
    phone: "+40 123",
    international_phone: "+40 123",
    website_url: "https://example.com",
    rating: 4.8,
    price_level: 2,
    reviews_count: 1411,
    google_rating: 4.8,
    google_user_rating_count: 1411,
    apify_review_count: null,
    apify_rating_avg: null,
    rating_count_for_score: 1411,
    bayesian_rating: 4.7,
    rating_score_0_100: 92,
    popularity_score_0_100: 80,
    rating_confidence_0_100: 95,
    price_min_ron: null,
    price_max_ron: null,
    map_visibility_score: 89,
    map_visibility_rank: 1,
    map_min_zoom_global: 12,
    ai_card_summary: "Calm coffee and work spot.",
    ai_place_type_summary: "Cafe",
    ai_vibe: "calm",
    ai_what_to_expect: "Quiet tables.",
    ai_food_and_drinks: "Coffee.",
    ai_price: "mid",
    ai_service: "friendly",
    ai_the_move: "Go daytime.",
    ai_watch_out: null,
    ai_tags: ["calm", "coffee"],
    ai_tags_json: [],
    ai_confidence: 0.8,
    axis_quiet_lively: 20,
    axis_work_social: 40,
    axis_day_night: 30,
    axis_casual_premium: 40,
    axis_drinks_food: 70,
    axis_local_tourist: 30,
    axis_cheap_expensive: 50,
    axis_traditional_experimental: 45,
    review_photo_count: 1,
    vibe_photo_count: 2,
    primary_photo_path: "google/ChIJ123/vibe/photo.jpg",
    primary_photo_url: "https://example.com/photo.jpg",
    primary_photo_width: 1200,
    primary_photo_height: 900,
    primary_photo_source: "vibe",
    total_photo_count: 3,
    opening_hours: { openNow: true },
    serves: ["coffee"],
    features: { dineIn: true },
    google_details: { paymentOptions: {} },
    apify_details: { languageCounts: {} },
    ai_details: { model: "gpt" },
    photo_details: { primaryPhotoFile: "photo.jpg" },
    attributes: {
      raw_cuisine_style: "Coffee, Desserts"
    },
    ...overrides
  };
}

describe("place details mapper", () => {
  it("maps rich place rows to place details", () => {
    expect(mapPlaceDetailRow(placeDetailRow())).toEqual<PlaceDetails>({
      id: 123,
      source: "google",
      sourceId: "ChIJ123",
      name: "Seneca Anticafe",
      country: "romania",
      city: "bucharest",
      category: "cafe",
      primaryType: "cafe",
      types: ["cafe", "food"],
      latitude: 44.43,
      longitude: 26.1,
      formattedAddress: "Bucharest",
      shortFormattedAddress: "Bucharest",
      businessStatus: "OPERATIONAL",
      googleMapsUri: "https://maps.google.com/example",
      phone: "+40 123",
      internationalPhone: "+40 123",
      websiteUrl: "https://example.com",
      rating: 4.8,
      priceLevel: 2,
      numberOfReviews: 1411,
      googleRating: 4.8,
      googleUserRatingCount: 1411,
      apifyReviewCount: null,
      apifyRatingAvg: null,
      ratingCountForScore: 1411,
      bayesianRating: 4.7,
      ratingScore: 92,
      popularityScore: 80,
      ratingConfidenceScore: 95,
      priceMinRon: null,
      priceMaxRon: null,
      mapVisibilityScore: 89,
      mapVisibilityRank: 1,
      mapMinZoomGlobal: 12,
      aiCardSummary: "Calm coffee and work spot.",
      aiPlaceTypeSummary: "Cafe",
      aiVibe: "calm",
      aiWhatToExpect: "Quiet tables.",
      aiFoodAndDrinks: "Coffee.",
      aiPrice: "mid",
      aiService: "friendly",
      aiTheMove: "Go daytime.",
      aiWatchOut: null,
      aiTags: ["calm", "coffee"],
      aiTagsJson: [],
      aiConfidence: 0.8,
      axisQuietLively: 20,
      axisWorkSocial: 40,
      axisDayNight: 30,
      axisCasualPremium: 40,
      axisDrinksFood: 70,
      axisLocalTourist: 30,
      axisCheapExpensive: 50,
      axisTraditionalExperimental: 45,
      reviewPhotoCount: 1,
      vibePhotoCount: 2,
      primaryPhoto: {
        path: "google/ChIJ123/vibe/photo.jpg",
        url: "https://example.com/photo.jpg",
        width: 1200,
        height: 900,
        source: "vibe"
      },
      totalPhotoCount: 3,
      openingHours: { openNow: true },
      serves: ["coffee"],
      features: { dineIn: true },
      googleDetails: { paymentOptions: {} },
      apifyDetails: { languageCounts: {} },
      aiDetails: { model: "gpt" },
      photoDetails: { primaryPhotoFile: "photo.jpg" },
      rawCuisineStyle: "Coffee, Desserts",
      isSaved: false,
      savedCollectionIds: [],
      reaction: null
    });
  });
});
