export const API_PREFIX = "/v1";

export enum AppRoute {
  Health = "/health",
  SupabaseHealth = "/health/supabase",
  Me = "/me",
  MeReactions = "/me/reactions",
  MeSavedIds = "/me/saved/ids",
  MeSaved = "/me/saved",
  MePlaceReaction = "/me/places/:placeId/reaction",
  MeSavedCollection = "/me/saved/collections/:collectionId",
  MeSavedPlaces = "/me/saved/places",
  MeSavedPlace = "/me/saved/places/:placeId",
  MeSavedCollections = "/me/saved/collections",
  MeSavedCollectionPlaces = "/me/saved/collections/:collectionId/places",
  MeSavedCollectionPlace = "/me/saved/collections/:collectionId/places/:placeId",
  MeSavedCollectionPlacesOrder = "/me/saved/collections/:collectionId/places/order",
  OnboardingComplete = "/onboarding/complete",
  MapPlaces = "/map/places",
  MapConfig = "/map/config",
  MapTile = "/map/tiles/:z/:x/:y.mvt",
  Place = "/places/:placeId",
  SearchPlaces = "/search/places",
  FeedPlaces = "/feed/places",
  Cities = "/cities",
  Events = "/events",
  SwaggerDocs = "/swagger/docs",
  SwaggerOpenApiJson = "/swagger/openapi.json"
}

export const VersionedAppRoute = {
  health: `${API_PREFIX}${AppRoute.Health}`,
  supabaseHealth: `${API_PREFIX}${AppRoute.SupabaseHealth}`,
  me: `${API_PREFIX}${AppRoute.Me}`,
  meReactions: `${API_PREFIX}${AppRoute.MeReactions}`,
  meSavedIds: `${API_PREFIX}${AppRoute.MeSavedIds}`,
  meSaved: `${API_PREFIX}${AppRoute.MeSaved}`,
  mePlaceReaction: `${API_PREFIX}${AppRoute.MePlaceReaction}`,
  meSavedCollection: `${API_PREFIX}${AppRoute.MeSavedCollection}`,
  meSavedPlaces: `${API_PREFIX}${AppRoute.MeSavedPlaces}`,
  meSavedPlace: `${API_PREFIX}${AppRoute.MeSavedPlace}`,
  meSavedCollections: `${API_PREFIX}${AppRoute.MeSavedCollections}`,
  meSavedCollectionPlaces: `${API_PREFIX}${AppRoute.MeSavedCollectionPlaces}`,
  meSavedCollectionPlace: `${API_PREFIX}${AppRoute.MeSavedCollectionPlace}`,
  meSavedCollectionPlacesOrder: `${API_PREFIX}${AppRoute.MeSavedCollectionPlacesOrder}`,
  onboardingComplete: `${API_PREFIX}${AppRoute.OnboardingComplete}`,
  mapPlaces: `${API_PREFIX}${AppRoute.MapPlaces}`,
  mapConfig: `${API_PREFIX}${AppRoute.MapConfig}`,
  mapTile: `${API_PREFIX}${AppRoute.MapTile}`,
  place: `${API_PREFIX}${AppRoute.Place}`,
  searchPlaces: `${API_PREFIX}${AppRoute.SearchPlaces}`,
  feedPlaces: `${API_PREFIX}${AppRoute.FeedPlaces}`,
  cities: `${API_PREFIX}${AppRoute.Cities}`,
  events: `${API_PREFIX}${AppRoute.Events}`,
  swaggerDocs: `${API_PREFIX}${AppRoute.SwaggerDocs}`,
  swaggerOpenApiJson: `${API_PREFIX}${AppRoute.SwaggerOpenApiJson}`
} as const;
