create or replace function public.map_places_in_bbox(
  sw_lat double precision,
  sw_lng double precision,
  ne_lat double precision,
  ne_lng double precision,
  result_limit integer default 100
)
returns table (
  id bigint,
  source text,
  source_id text,
  name text,
  category text,
  primary_type text,
  latitude double precision,
  longitude double precision,
  rating numeric,
  price_level smallint,
  reviews_count integer,
  google_rating numeric,
  google_user_rating_count integer,
  rating_score_0_100 numeric,
  popularity_score_0_100 numeric,
  map_visibility_score numeric,
  map_visibility_rank integer,
  primary_photo_path text,
  primary_photo_url text,
  primary_photo_width integer,
  primary_photo_height integer,
  primary_photo_source text
)
language sql
stable
as $$
  select
    p.id,
    p.source,
    p.source_id,
    p.name,
    p.category,
    p.primary_type,
    p.latitude,
    p.longitude,
    p.rating,
    p.price_level,
    p.reviews_count,
    p.google_rating,
    p.google_user_rating_count,
    p.rating_score_0_100,
    p.popularity_score_0_100,
    p.map_visibility_score,
    p.map_visibility_rank,
    p.primary_photo_path,
    ph.public_url as primary_photo_url,
    ph.width as primary_photo_width,
    ph.height as primary_photo_height,
    ph.photo_source as primary_photo_source
  from public.places p
  left join public.place_photos ph
    on ph.place_source = p.source
   and ph.place_source_id = p.source_id
   and ph.storage_path = p.primary_photo_path
  where p.geom && st_makeenvelope(sw_lng, sw_lat, ne_lng, ne_lat, 4326)
  order by
    p.map_visibility_score desc,
    p.rating_score_0_100 desc nulls last,
    p.popularity_score_0_100 desc nulls last,
    p.google_rating desc nulls last,
    p.google_user_rating_count desc nulls last,
    p.id asc
  limit least(greatest(coalesce(result_limit, 100), 1), 1000);
$$;

create or replace function public.place_details_by_id(place_id bigint)
returns table (
  id bigint,
  source text,
  source_id text,
  name text,
  country text,
  city text,
  category text,
  primary_type text,
  types text[],
  latitude double precision,
  longitude double precision,
  formatted_address text,
  short_formatted_address text,
  business_status text,
  google_maps_uri text,
  phone text,
  international_phone text,
  website_url text,
  rating numeric,
  price_level smallint,
  reviews_count integer,
  google_rating numeric,
  google_user_rating_count integer,
  apify_review_count integer,
  apify_rating_avg numeric,
  rating_count_for_score integer,
  bayesian_rating numeric,
  rating_score_0_100 numeric,
  popularity_score_0_100 numeric,
  rating_confidence_0_100 numeric,
  price_min_ron numeric,
  price_max_ron numeric,
  map_visibility_score numeric,
  map_visibility_rank integer,
  map_min_zoom_global smallint,
  ai_card_summary text,
  ai_place_type_summary text,
  ai_vibe text,
  ai_what_to_expect text,
  ai_food_and_drinks text,
  ai_price text,
  ai_service text,
  ai_the_move text,
  ai_watch_out text,
  ai_tags text[],
  ai_tags_json jsonb,
  ai_confidence numeric,
  axis_quiet_lively smallint,
  axis_work_social smallint,
  axis_day_night smallint,
  axis_casual_premium smallint,
  axis_drinks_food smallint,
  axis_local_tourist smallint,
  axis_cheap_expensive smallint,
  axis_traditional_experimental smallint,
  review_photo_count integer,
  vibe_photo_count integer,
  primary_photo_path text,
  primary_photo_url text,
  primary_photo_width integer,
  primary_photo_height integer,
  primary_photo_source text,
  total_photo_count integer,
  opening_hours jsonb,
  serves jsonb,
  features jsonb,
  google_details jsonb,
  apify_details jsonb,
  ai_details jsonb,
  photo_details jsonb,
  attributes jsonb
)
language sql
stable
as $$
  select
    p.id,
    p.source,
    p.source_id,
    p.name,
    p.country,
    p.city,
    p.category,
    p.primary_type,
    p.types,
    p.latitude,
    p.longitude,
    p.formatted_address,
    p.short_formatted_address,
    p.business_status,
    p.google_maps_uri,
    p.phone,
    p.international_phone,
    p.website_url,
    p.rating,
    p.price_level,
    p.reviews_count,
    p.google_rating,
    p.google_user_rating_count,
    p.apify_review_count,
    p.apify_rating_avg,
    p.rating_count_for_score,
    p.bayesian_rating,
    p.rating_score_0_100,
    p.popularity_score_0_100,
    p.rating_confidence_0_100,
    p.price_min_ron,
    p.price_max_ron,
    p.map_visibility_score,
    p.map_visibility_rank,
    p.map_min_zoom_global,
    p.ai_card_summary,
    p.ai_place_type_summary,
    p.ai_vibe,
    p.ai_what_to_expect,
    p.ai_food_and_drinks,
    p.ai_price,
    p.ai_service,
    p.ai_the_move,
    p.ai_watch_out,
    p.ai_tags,
    p.ai_tags_json,
    p.ai_confidence,
    p.axis_quiet_lively,
    p.axis_work_social,
    p.axis_day_night,
    p.axis_casual_premium,
    p.axis_drinks_food,
    p.axis_local_tourist,
    p.axis_cheap_expensive,
    p.axis_traditional_experimental,
    p.review_photo_count,
    p.vibe_photo_count,
    p.primary_photo_path,
    ph.public_url as primary_photo_url,
    ph.width as primary_photo_width,
    ph.height as primary_photo_height,
    ph.photo_source as primary_photo_source,
    p.total_photo_count,
    p.opening_hours,
    p.serves,
    p.features,
    p.google_details,
    p.apify_details,
    p.ai_details,
    p.photo_details,
    p.attributes
  from public.places p
  left join public.place_photos ph
    on ph.place_source = p.source
   and ph.place_source_id = p.source_id
   and ph.storage_path = p.primary_photo_path
  where p.id = $1
  limit 1;
$$;
